name: Deploy Frontend to VPS

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            echo "🚀 Starting frontend deployment..."

            # Create app directory if it doesn't exist
            mkdir -p ${{ secrets.APP_PATH }}
            cd ${{ secrets.APP_PATH }}

            # Clone repository if it doesn't exist, otherwise pull latest
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git fetch origin
              git reset --hard origin/master
            fi

            # Install Node.js if not available
            if ! command -v node &> /dev/null; then
              # Download and install nvm:
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
              # in lieu of restarting the shell
              . "$HOME/.nvm/nvm.sh"
              # Download and install Node.js:
              nvm install 22
              nvm use 22
            fi

            # Create environment file for production
            cat > .env << 'EOF'
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
            EOF

            # Install dependencies and build
            npm ci
            npm run build

            # Create backup of current build
            if [ -d "/var/www/html/frontend" ]; then
              mv /var/www/html/frontend /var/www/html/frontend.backup.$(date +%Y%m%d-%H%M%S)
            fi

            # Copy build files to web directory
            mkdir -p /var/www/html/frontend
            cp -r dist/* /var/www/html/frontend/

            # Set proper permissions
            chown -R www-data:www-data /var/www/html/frontend
            chmod -R 755 /var/www/html/frontend

            echo "✅ Frontend deployment completed successfully!"

      - name: Health Check
        run: |
          sleep 10
          curl -f https://devopspage.khoipn.id.vn/ || exit 1
